# Generated by Django 3.1.6 on 2021-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
