# Generated by Django 3.1.6 on 2021-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_code',
            field=models.CharField(default='2fe6a7', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
