# Generated by Django 3.1.6 on 2021-04-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210409_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, default='e5fdc5', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_code',
            field=models.CharField(default='9d18f2', max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.question'),
        ),
    ]
