# Generated by Django 3.1.6 on 2021-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210412_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, default='20e570', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_code',
            field=models.CharField(default='957f0a', max_length=200),
        ),
    ]
